spring:
  jackson:
    default-property-inclusion: non_null
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://192.168.0.16:8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.0.11:8080/eureka/
hystrix:
  shareSecurityContext: true
signing:
  key: "{cipher}100bbcf1f144b39ae6c02180b9e9bd71a11b79e2895a0b3ce1a4c055d544c6232de804e6d3daf0c2b70ebfac5a9a7520"