spring:
  cloud:
    stream:
     bindings:
       output:
         destination: messages
         content-type: application/json

       input:
         destination: messages
         content-type: application/json
         group: training

security:
  oauth2:
    resource:
      filter-order: 3